document.addEventListener('DOMContentLoaded',()=>{document.getElementById('login-form')?.addEventListener('submit',loginUser);document.getElementById('register-form')?.addEventListener('submit',registerUser);});
function showMessage(id,text,success=false){const e=document.getElementById(id);if(e){e.textContent=text;e.className=success?'success-msg visible':'error-msg visible';}}
async function getCurrentUser(){const {data:{user}}=await supabase.auth.getUser();return user;}
async function getUserRole(){const u=await getCurrentUser();if(!u)return null;const {data}=await supabase.from('profiles').select('*').eq('id',u.id).single();return data;}
function redirectBasedOnRole(role){location.href=role==='admin'?'admin.html':role==='security'?'security.html':role==='student'?'student.html':'index.html';}
async function loginUser(e){e.preventDefault();const mail=document.getElementById('email').value.trim(),pass=document.getElementById('password').value;const {data,error}=await supabase.auth.signInWithPassword({email:mail,password:pass});if(error||!data.user)return showMessage('login-error','Invalid email or password.');const p=await getUserRole();if(!p)return showMessage('login-error','Your profile is not ready. Please contact an administrator.');redirectBasedOnRole(p.role);}
async function registerUser(e){e.preventDefault();const n=document.getElementById('name').value.trim(),mail=document.getElementById('email').value.trim(),pass=document.getElementById('password').value,ph=document.getElementById('phone').value.trim(),type=document.getElementById('vehicle_type').value,vehicle_number=document.getElementById('vehicle_number').value.trim().toUpperCase();if(!vehicle_number)return showMessage('register-error','Please enter your vehicle number.');const details={name:n,phone:ph,vehicle_number,vehicle_type:type};const {data,error}=await supabase.auth.signUp({email:mail,password:pass,options:{data:details}});if(error)return showMessage('register-error','Could not create the account. Check the email and password.');if(!data.session)return showMessage('register-error','Account created. Please confirm your email, then log in.',true);const {error:pe}=await supabase.from('profiles').update({...details,email:mail}).eq('id',data.user.id);if(pe)return showMessage('register-error','Account created, but vehicle details could not be saved. Please log in and try again.');redirectBasedOnRole('student');}
async function logoutUser(){await supabase.auth.signOut();location.href='index.html';}
async function checkAuthAndRole(expected){const p=await getUserRole();if(!p){location.href='login.html';return null;}if(expected&&p.role!==expected){redirectBasedOnRole(p.role);return null;}return p;}
