let profile,selectedSlotId,currentSession;
document.addEventListener('DOMContentLoaded',async()=>{profile=await checkAuthAndRole('student');if(!profile)return;welcomeMessage.textContent=`Welcome, ${profile.name||'Student'}`;vehicleDetails.innerHTML=`<p><b>Vehicle Number:</b> ${profile.vehicle_number||'Not set'}</p><p><b>Vehicle Type:</b> ${(profile.vehicle_type||'').toUpperCase()}</p>`;await refreshStudent();});
async function refreshStudent(){const {data}=await supabase.from('parking_sessions').select('*,parking_slots(slot_number)').eq('user_id',profile.id).in('status',['pending','active']).order('created_at',{ascending:false}).limit(1);currentSession=data?.[0];if(currentSession)showSession();else{currentSessionSection.classList.add('hidden');bookSlotSection.classList.remove('hidden');loadSlots();}loadHistory();}
function showSession(){bookSlotSection.classList.add('hidden');currentSessionSection.classList.remove('hidden');sessionDetails.innerHTML=`<p><b>Slot:</b> ${currentSession.parking_slots.slot_number}</p><p><b>Status:</b> <span class="badge badge-${currentSession.status}">${currentSession.status}</span></p>`;qrCode.innerHTML='';new QRCode(qrCode,{text:currentSession.qr_token,width:220,height:220,correctLevel:QRCode.CorrectLevel.H});downloadQrBtn.classList.remove('hidden');}
async function loadSlots(){const {data,error}=await supabase.from('parking_slots').select('*').eq('vehicle_type',profile.vehicle_type).order('slot_number');if(error)return;slotsContainer.innerHTML=data.map(s=>`<button class="slot ${s.status} ${selectedSlotId===s.id?'selected':''}" ${s.status!=='available'?'disabled':''} onclick="selectSlot('${s.id}')"><b>${s.slot_number}</b><small>${s.vehicle_type}</small><span>${s.status}</span></button>`).join('');}
function selectSlot(id){selectedSlotId=id;bookBtn.classList.remove('hidden');loadSlots();}
function makeToken(){return `PARK-${crypto.getRandomValues(new Uint32Array(1))[0].toString(16).toUpperCase()}-${Date.now().toString(36).toUpperCase()}`;}
async function createParkingSession(){if(!selectedSlotId)return showMessage('booking-error','Please select a parking slot.');const {error}=await supabase.rpc('create_parking_session',{p_slot_id:selectedSlotId,p_token:makeToken()});if(error)return showMessage('booking-error',error.message.includes('active')?'You already have an active parking session.':'Parking slot is no longer available.');selectedSlotId=null;refreshStudent();}
async function loadHistory(){const {data}=await supabase.from('parking_sessions').select('*,parking_slots(slot_number)').eq('user_id',profile.id).in('status',['completed','cancelled']).order('created_at',{ascending:false});historyContainer.innerHTML=!data?.length?'<p class="muted">No parking history yet.</p>':`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Vehicle</th><th>Slot</th><th>Entry</th><th>Exit</th><th>Status</th></tr></thead><tbody>${data.map(s=>`<tr><td>${new Date(s.created_at).toLocaleDateString()}</td><td>${s.vehicle_number}</td><td>${s.parking_slots.slot_number}</td><td>${fmt(s.entry_time)}</td><td>${fmt(s.exit_time)}</td><td><span class="badge badge-${s.status}">${s.status}</span></td></tr>`).join('')}</tbody></table></div>`;}
function fmt(v){return v?new Date(v).toLocaleString():'—';}
function downloadQR(){const img=qrCode.querySelector('img')||qrCode.querySelector('canvas');const a=document.createElement('a');a.download='parking-qr.png';a.href=img.src||img.toDataURL('image/png');a.click();}
