/* ParkEase is a front-end demo. localStorage keeps mock data between refreshes. */
const STORAGE_KEY='parkease-demo-state';
const defaultState={user:null,selectedZone:null,zones:[{id:'A1',name:'North Gate',available:8,total:12,duration:'2 hours'},{id:'B2',name:'Library Block',available:3,total:10,duration:'2 hours'},{id:'C1',name:'Sports Complex',available:0,total:8,duration:'3 hours'},{id:'D4',name:'Science Wing',available:11,total:15,duration:'2 hours'}]};
let state=JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(defaultState),lastFocus;
const $=selector=>document.querySelector(selector);
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
const routes=['landing','login','pass','scanner','dashboard'];

function route(name){routes.forEach(view=>{const el=$(`#${view}-view`);el.hidden=view!==name;});if(name==='dashboard')loadDashboard();if(name==='pass')renderPass();if(name==='scanner')renderScanner();$('#main-content').focus?.();}
function setMessage(id,text,error=false){const el=$(id);el.textContent=text;el.classList.toggle('error',error);}
function setTab(role){const student=role==='student';$('#student-form').hidden=!student;$('#admin-form').hidden=student;$('#student-tab').classList.toggle('active',student);$('#admin-tab').classList.toggle('active',!student);$('#student-tab').setAttribute('aria-selected',student);$('#admin-tab').setAttribute('aria-selected',!student);(student?$('#student-name'):$('#admin-name')).focus();}
function token(){return `PARK-${crypto.getRandomValues(new Uint32Array(1))[0].toString(16).toUpperCase()}-${Date.now().toString(36).toUpperCase()}`;}

function handleStudentLogin(event){event.preventDefault();const name=$('#student-name').value.trim(),vehicle=$('#vehicle-number').value.trim().toUpperCase(),type=$('#vehicle-type').value;if(!name||!vehicle)return setMessage('#student-message','Please enter your name and vehicle number.',true);state.user={role:'student',name,vehicle,type,qr:token(),createdAt:new Date().toISOString()};save();route('pass');}
function handleAdminLogin(event){event.preventDefault();const name=$('#admin-name').value.trim(),pin=$('#admin-pin').value.trim();if(!name||pin.length<4)return setMessage('#admin-message','Enter your name and a four-digit access PIN.',true);state.user={role:'admin',name};save();route('dashboard');}
function generateUserQR(){if(!state.user?.qr)state.user.qr=token();else state.user.qr=token();save();renderPass();}
function qrSvg(value){let seed=0;for(const char of value)seed=(seed*31+char.charCodeAt(0))>>>0;const bits=Array.from({length:21*21},(_,i)=>((seed=((seed*1664525+1013904223)>>>0))>>>30)&1);const cells=[];for(let y=0;y<21;y++)for(let x=0;x<21;x++)if(bits[y*21+x])cells.push(`<rect x="${x}" y="${y}" width="1" height="1"/>`);return `<svg viewBox="0 0 21 21" role="img" aria-label="QR pass ${value}"><rect width="21" height="21" fill="white"/><g fill="#18342d">${cells.join('')}</g></svg>`;}
function renderPass(){if(!state.user||state.user.role!=='student'){route('login');return;}const u=state.user;$('#qr-visual').innerHTML=qrSvg(u.qr);$('#qr-token').textContent=u.qr;$('#pass-details').innerHTML=`<dt>Name</dt><dd>${u.name}</dd><dt>Vehicle</dt><dd>${u.vehicle}</dd><dt>Type</dt><dd>${u.type}</dd><dt>Status</dt><dd>Ready to scan</dd>`;}
async function fetchParkingData(){await new Promise(resolve=>setTimeout(resolve,220));return {status:'success',zones:state.zones};}
async function loadDashboard(){const admin=state.user?.role==='admin';$('#dashboard-intro').textContent=admin?'Admin controls are available for each zone.':'Choose an available space. Sign in as a student to reserve it.';$('#status-message').textContent='Refreshing current availability…';const response=await fetchParkingData();const grid=$('#parking-grid');grid.innerHTML='';response.zones.forEach(zone=>grid.append(zoneCard(zone,admin)));$('#status-message').textContent='Availability updated just now.';}
function zoneCard(zone,admin){const full=zone.available===0,low=zone.available>0&&zone.available<=3,card=document.createElement('article');card.className='zone-card';card.innerHTML=`<p class="eyebrow">ZONE ${zone.id}</p><h2>${zone.name}</h2><p class="availability ${full?'full':low?'low':''}">${full?'Currently full':`${zone.available} of ${zone.total} spaces available`}</p><p>Maximum stay: ${zone.duration}</p>`;if(admin){const tools=document.createElement('div');tools.className='admin-tools';tools.innerHTML='<button class="button secondary" type="button">− Space</button><button class="button primary" type="button">+ Space</button>';tools.children[0].onclick=()=>updateSpaces(zone.id,-1);tools.children[1].onclick=()=>updateSpaces(zone.id,1);card.append(tools);}else{const button=document.createElement('button');button.className='button primary';button.type='button';button.disabled=full;button.textContent=full?'No spaces available':'Choose this zone';button.onclick=()=>confirmParking(zone);card.append(button);}return card;}
function updateSpaces(id,change){const zone=state.zones.find(item=>item.id===id);zone.available=Math.max(0,Math.min(zone.total,zone.available+change));save();loadDashboard();}
function confirmParking(zone){if(!state.user||state.user.role!=='student'){route('login');setMessage('#student-message','Sign in first to create your parking pass.');return;}if(zone.available<1)return;zone.available--;state.selectedZone=zone.id;save();lastFocus=document.activeElement;const time=new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date());$('#modal-details').innerHTML=`<p><strong>Parking zone</strong> ${zone.id} · ${zone.name}</p><p><strong>Vehicle</strong> ${state.user.vehicle}</p><p><strong>Start time</strong> ${time}</p><p><strong>Status</strong> Active</p>`;$('#confirmation-modal').hidden=false;$('#done-button').focus();}
function closeModal(){$('#confirmation-modal').hidden=true;lastFocus?.focus();}
function renderScanner(){const hasPass=state.user?.role==='student';$('#scan-result').innerHTML=hasPass?'<h2>Ready to verify</h2><p>Press simulate scan to verify the active student pass.</p>':'<h2>No student pass loaded</h2><p>Create a student parking pass first, then return here.</p>';}
function handleQRScan(){const result=$('#scan-result');if(!state.user||state.user.role!=='student'){result.innerHTML='<h2>Pass not found</h2><p>Create a student pass before scanning. This keeps the demo safe and predictable.</p>';return;}const zone=state.zones.find(item=>item.id===state.selectedZone);result.innerHTML=`<h2>Pass verified ✓</h2><p><strong>${state.user.name}</strong> · ${state.user.vehicle}</p><p>QR token: ${state.user.qr}</p><p>${zone?`Allotted zone: ${zone.id} · ${zone.name}`:'Select a parking zone to complete allotment.'}</p>`;}

document.querySelectorAll('[data-route]').forEach(button=>button.addEventListener('click',()=>route(button.dataset.route)));
$('#student-tab').addEventListener('click',()=>setTab('student'));$('#admin-tab').addEventListener('click',()=>setTab('admin'));$('#student-form').addEventListener('submit',handleStudentLogin);$('#admin-form').addEventListener('submit',handleAdminLogin);$('#regenerate-qr').addEventListener('click',generateUserQR);$('#scan-button').addEventListener('click',handleQRScan);$('#refresh-data').addEventListener('click',loadDashboard);$('#close-modal').addEventListener('click',closeModal);$('#done-button').addEventListener('click',closeModal);document.querySelector('[data-close-modal]').addEventListener('click',closeModal);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('#confirmation-modal').hidden)closeModal();});
